name: Release Obsidian plugin

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Update manifest version
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          jq --arg version "$tag" '.version = $version' manifest.json > temp.json && mv temp.json manifest.json

      - name: Create and checkout new branch
        run: |
          git checkout -b update-version-${{ github.ref_name }}

      - name: Commit updated manifest
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add manifest.json
          git commit -m "Automatically update manifest version to ${{ github.ref_name }} by GitHub Actions"
          git push origin update-version-${{ github.ref_name }}

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Update manifest version to ${{ github.ref_name }}"
          pr_body: "Automatically update manifest version by GitHub Actions"
          destination_branch: "main"
          source_branch: "update-version-${{ github.ref_name }}"

      - name: Auto merge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge_method: merge
          commit_message_template: "Merge pull request for version update"
          pull_request_filter_labels: "automerge"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --title="$tag" \
            --draft \
            main.js manifest.json
